# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 425946af7cdb4f7e853066f326b80754d2f020e913d742158f95e4b81d369e7692fb23ae3ffe87134ac2b62eb0ad6bde52e475eb79e755e0e51c1de4d5d4b627

test:
  secret_key_base: 246e0ff7d7402122ac9b7208e0d9969117e26c60da2b9ecc0aebb31473845d6f036bff81273ca8f37267df8ff00d3b31f7431609ef71a3d612e5fdb98f905fbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
